### ISSUE TITLE
no-trailing-spaces in comment breaks TypeDoc

### ISSUE THREAD

**Issue by l1br3** [standard/eslint-config-standard#144]
TypeDoc uses a kind of markdown syntax where the double-space at end of line for a line break.
I think disable the rule for comments is fine as anyway but it's only my own opinion.
The standard advice for that case is to jump on something important by it actually breaks my doc which is very important.
I could use something else than TypeDoc but it's a very performant tool.

**Comment by l1br3** [comment]
https://github.com/standard/eslint-config-standard/pull/145

**Comment by LinusU** [comment]
Personally, I'm really not a fan of trailing spaces since they are 1) often invisible in editors and 2) often stripped by editors.

In many markdown parsers you can end the line with a backslash to signify that you want a line break, maybe that works with TypeDoc? Otherwise I think it would be a great feature request :+1:

```
/**
 * Line 1\
 * Line 2
 */
export class DocumentMe {}
```

**Comment by l1br3** [comment]
Thanks for the suggestion, works perfectly ! 
That's even better than double spaces !
