### ISSUE TITLE
Incompatibility with eslint in vscode

### ISSUE THREAD

**Issue by greenhat616** [standard/eslint-config-standard#179]
**What version of this package are you using?**
v16+
**What operating system, Node.js, and npm version?**
Ubuntu 20.04 LTS, WSL 2
Node.js v14
yarn v2.3.3(berry, PnP enabled)

**What happened?**
As illustrated in https://github.com/microsoft/vscode-eslint/issues/1126, after upgrading to v16, the eslint plugin in vscode is not work
**What did you expect to happen?**
cooperate to solve it.
**Are you willing to submit a pull request to fix this bug?**
Maybe, if the reason of the  issue is confirmed

**Comment by feross** [comment]
I'm sorry that you're facing this issue. As far as I can tell, this isn't an issue in `eslint-config-standard`. This package is literally just a JSON file of rules. I don't have the bandwidth to debug package managers like `yarn` which I do not personally use.

Maybe this is due to the upgraded peer dependency on ESLint 7 instead 6. If you find a solution and there's something we can do on our end to fix this, please send a PR.
