### ISSUE TITLE
Cannot find module 'eslint-plugin-node'

### ISSUE THREAD

**Issue by CyrilKrylatov** [standard/eslint-config-standard#226]
**What version of this package are you using?**
```json
"eslint-config-standard": "^16.0.3",
```

**What operating system, Node.js, and npm version?**
macOS 12.3 (21E230), node v17.7.2, yarn 1.22.5

**What happened?**

I was following the README file, I installed those packages (with yarn under the `--dev` flag):

```json
        "eslint": "^8.13.0",
        "eslint-config-standard": "^16.0.3",
        "eslint-plugin-import": "^2.26.0",
        "eslint-plugin-n": "^15.1.0",
        "eslint-plugin-promise": "^6.0.0",
```

And in my `.eslintrc.json` file:
```json
{
  "extends": ["standard"]
}
```

But my IDE (WebStorm) still give me the following error:

> Error: Failed to load plugin 'node' declared in '.eslintrc.json » eslint-config-standard': Cannot find module 'eslint-plugin-node'

**What did you expect to happen?**

To not have the error about `eslint-plugin-node` not installed since the README do tells to use `eslint-plugin-n` instead.

**Are you willing to submit a pull request to fix this bug?**

I'm so sorry I don't have the developer background to do that. :(

**Comment by BobbyWibowo** [comment]
`eslint-config-standard@16` still explicitly requires `eslint-plugin-node` instead of `eslint-plugin-n`
It's also documented as such in the NPM readme, https://www.npmjs.com/package/eslint-config-standard, which still uses version 16 as the stable version

`eslint-config-standard@17` switches to using `eslint-plugin-n`, however it's still marked as a `next` version

Basically, you should not have used the GitHub readme as reference, as it's essentially the "dev" version

**Comment by voxpelli** [comment]
Maybe we should add a note about this @Divlo?
